import { PlatformsData } from "./types";

export const platformsData: PlatformsData = {
  updatedAt: "2026-03-28",
  platforms: [
    // ═══════════════════════════════════════
    // 国内 Coding Plan
    // ═══════════════════════════════════════
    {
      id: "aliyun", name: "阿里云百炼", region: "cn", category: "plan",
      badge: "首月 ¥7.9", badgeColor: "green",
      desc: ["千问系列 + 第三方模型", "限时首月特惠 · 续费次月半价"],
      plans: [
        { name: "Lite 基础版", price: 40, priceLabel: "¥40/月", firstMonth: "首月 ¥7.9 → 续费 ¥20", quota5h: "1,200 次", quotaWeek: "9,000 次", quotaMonth: "18,000 次", popular: true, tags: ["qwen3.5-plus", "glm-4.7", "kimi-k2.5"] },
        { name: "Pro 高阶版", price: 200, priceLabel: "¥200/月", firstMonth: "首月 ¥39.9 → 续费 ¥100", quota5h: "6,000 次", quotaWeek: "45,000 次", quotaMonth: "90,000 次", tags: ["qwen3-max", "qwen3-coder", "全部模型"] },
      ],
      models: ["qwen3.5-plus", "qwen3-max", "qwen3-coder-next", "qwen3-coder-plus", "glm-4.7", "kimi-k2.5"],
      tools: ["Claude Code", "Cursor", "Cline", "OpenCode", "Codex CLI"],
      notice: "仅主账号可用，不支持 RAM 用户 · 禁止 API 调用 · 不支持退订退款 · 一次提问约触发 5-30 次模型调用",
      link: "https://help.aliyun.com/zh/model-studio/coding-plan", updatedAt: "2026-03-28",
    },
    {
      id: "zhipu", name: "智谱 GLM", region: "cn", category: "plan",
      badge: "含 MCP 工具", badgeColor: "purple",
      desc: ["GLM-5 SWE-bench 第一梯队", "连续包季9折 · 包年7折"],
      plans: [
        { name: "Lite 轻量级", price: 49, priceLabel: "¥49/月", quota5h: "~80 prompts", quotaWeek: "~400", tags: ["GLM-5", "GLM-4.7", "MCP 试用"] },
        { name: "Pro 最受欢迎", price: 149, priceLabel: "¥149/月", quota5h: "~400 prompts", quotaWeek: "~2,000", popular: true, tags: ["速度更快", "MCP 1000次/月"] },
        { name: "Max 量大管饱", price: 469, priceLabel: "¥469/月", quota5h: "~1,600 prompts", quotaWeek: "~8,000", tags: ["新模型首发", "高峰优先"] },
      ],
      models: ["GLM-5", "GLM-4.7", "GLM-4.6"], contextWindow: "200K",
      tools: ["Claude Code", "Roo Code", "Kilo Code", "Cline", "OpenCode", "Crush", "Goose", "Cursor 等 20+"],
      notice: "5h动态刷新 + 每7天重置 · MCP Lite 100/Pro 1000/Max 4000次 · GLM-5 消耗3倍额度（仅 Pro/Max）",
      link: "https://www.bigmodel.cn/glm-coding", updatedAt: "2026-03-28",
    },
    {
      id: "minimax", name: "MiniMax", region: "cn", category: "plan",
      badge: "100+ TPS", badgeColor: "yellow",
      desc: ["Mini 价格 Max 性能", "连续包年立省2月"],
      plans: [
        { name: "Starter · 标准版", price: 29, priceLabel: "¥29/月", quota5h: "40 prompts · ~50 TPS" },
        { name: "Plus · 极速版", price: 98, priceLabel: "¥98/月", quota5h: "100 prompts · ~100 TPS", popular: true },
        { name: "Max · 极速版", price: 199, priceLabel: "¥199/月", quota5h: "300 prompts · ~100 TPS" },
        { name: "Ultra · 极速版", price: 899, priceLabel: "¥899/月", quota5h: "2000 prompts · ~100 TPS" },
      ],
      models: ["M2.5", "M2.5-highspeed"],
      tools: ["Claude Code", "Roo Code", "Kilo Code", "Cline", "Codex CLI", "OpenCode", "Droid", "TRAE", "Grok CLI", "Cursor"],
      notice: "图像理解 MCP · 联网搜索 MCP",
      link: "https://platform.minimaxi.com/subscribe/token-plan", updatedAt: "2026-03-28",
    },
    {
      id: "kimi", name: "Kimi", region: "cn", category: "plan",
      badge: "含会员权益", badgeColor: "blue",
      desc: ["全面接入 K2.5", "年付最高立省 ¥240"],
      plans: [
        { name: "Andante 基础", price: 49, priceLabel: "¥49/月", quota5h: "300-1,200 次调用", tags: ["旗舰模型抢先体验"] },
        { name: "Moderato 推荐", price: 99, priceLabel: "¥99/月", quota5h: "更大额度", popular: true, tags: ["Claude Code", "Roo Code", "多设备共享"] },
      ],
      models: ["Kimi K2.5"],
      tools: ["Kimi CLI", "Claude Code", "Roo Code", "Kimi Code for VS Code"],
      notice: "额度每7天刷新不累积 · 最大并发30 · 工具适配限制严 · 仅限个人使用",
      link: "https://www.kimi.com/code", updatedAt: "2026-03-28",
    },
    {
      id: "tencent", name: "腾讯云", region: "cn", category: "plan",
      badge: "首月 ¥7.9", badgeColor: "green",
      desc: ["混元自研 + 顶尖第三方", "首月¥7.9 · 次月5折"],
      plans: [
        { name: "Lite 限时特惠", price: 40, priceLabel: "¥40/月", firstMonth: "首月 ¥7.9 → 次月 ¥20 → 原价 ¥40", quota5h: "~1,200 次", quotaWeek: "~9,000 次", quotaMonth: "~18,000 次", popular: true },
        { name: "Pro 专业首选", price: 200, priceLabel: "¥200/月", firstMonth: "首月 ¥39.9 → 次月 ¥100 → 原价 ¥200", quota5h: "~6,000 次", quotaWeek: "~45,000 次", quotaMonth: "~90,000 次" },
      ],
      models: ["Tencent HY 2.0 Instruct", "GLM-5", "Kimi-K2.5", "MiniMax-M2.5"],
      tools: ["OpenClaw", "CodeBuddy", "Claude Code", "Cline", "Cursor"],
      link: "https://curl.qcloud.com/Km11xLvs", updatedAt: "2026-03-28",
    },
    {
      id: "volcengine", name: "火山方舟", region: "cn", category: "plan",
      badge: "模型最多", badgeColor: "blue",
      desc: ["6 款模型自由切换 · Auto 调度", "首月2.5折"],
      plans: [
        { name: "Lite", price: 40, priceLabel: "¥40/月", firstMonth: "首月 ¥8.91 · 次月5折 ¥20", quota5h: "数倍 Claude Pro", popular: true, tags: ["Auto 模式", "6款模型"] },
        { name: "Pro", price: 200, priceLabel: "¥200/月", firstMonth: "首月 ¥44.91", quota5h: "5倍 Lite" },
      ],
      models: ["Doubao-Seed-2.0-Code", "Doubao-Seed-Code", "Kimi-K2.5", "Kimi-K2", "GLM-4.7", "DeepSeek-V3.2"],
      tools: ["Claude Code", "Cursor", "Cline", "Codex CLI", "Kilo Code"],
      notice: "⚠️ 高峰期超售：响应慢、频繁报错 · 退款条款苛刻",
      link: "https://volcengine.com/L/WmPIEgflQmE/", updatedAt: "2026-03-28",
    },
    {
      id: "baishan", name: "白山智算", region: "cn", category: "plan",
      badge: "送 ¥450", badgeColor: "yellow",
      desc: ["按量计费 · 无月费门槛", "注册送¥150 + 首次调用送¥300"],
      plans: [
        { name: "注册 + 实名认证", price: 0, priceLabel: "¥150 代金券", quota5h: "按 token 计量" },
        { name: "首次 API 调用", price: 0, priceLabel: "¥300 代金券", quota5h: "约3工作日到账", popular: true },
      ],
      models: ["MiniMax-M2.5", "GLM-5", "GLM-4.7", "DeepSeek", "Kimi", "Qwen"],
      tools: ["支持自定义 API Endpoint"],
      notice: "按量计费，无月费门槛。代金券用完后按实际 token 用量付费。",
      link: "https://ai.baishan.com/auth/login", updatedAt: "2026-03-28",
    },
    {
      id: "infini", name: "无问芯穹", region: "cn", category: "plan",
      badge: "OpenAI 协议", badgeColor: "purple",
      desc: ["一份订阅接入多款模型", "支持 OpenAI/Anthropic 协议"],
      plans: [
        { name: "Coding Lite", price: 40, priceLabel: "¥40/月", quota5h: "1,000 次", quotaWeek: "6,000 次", quotaMonth: "12,000 次", popular: true, tags: ["改Bug", "脚本", "文档"] },
        { name: "Coding Pro", price: 200, priceLabel: "¥200/月", quota5h: "5,000 次", quotaWeek: "30,000 次", quotaMonth: "60,000 次", tags: ["架构重构", "连续高频"] },
      ],
      models: ["deepseek-v3.2", "deepseek-v3.2-thinking", "minimax-m2.5", "minimax-m2.7", "glm-4.7", "glm-5", "kimi-k2.5"],
      tools: ["Claude Code", "Cursor", "Cline", "OpenCode 等"],
      link: "https://cloud.infini-ai.com/", updatedAt: "2026-03-28",
    },

    // ═══════════════════════════════════════
    // 国际产品
    // ═══════════════════════════════════════
    {
      id: "cursor", name: "Cursor", region: "intl", category: "ide",
      badge: "100万+ 用户", badgeColor: "green",
      desc: ["AI-First IDE · VS Code fork", "最大 AI IDE 社区"],
      plans: [
        { name: "Hobby", price: 0, priceLabel: "免费", quota5h: "2,000 补全/月", tags: ["有限"] },
        { name: "Pro", price: 20, priceLabel: "$20/月", quota5h: "500 fast requests", popular: true, tags: ["多模型", "Background Agents"] },
        { name: "Pro+", price: 60, priceLabel: "$60/月", quota5h: "更高限额", tags: ["优先模型"] },
        { name: "Business", price: 40, priceLabel: "$40/人/月", quota5h: "团队管理", tags: ["RBAC", "SAML SSO"] },
        { name: "Ultra", price: 200, priceLabel: "$200/月", quota5h: "最高限额", tags: ["重度用户"] },
      ],
      models: ["GPT-5", "Claude Sonnet 4.5", "Gemini 2.5 Pro"], contextWindow: "1M",
      tools: ["Cursor IDE（VS Code fork）"],
      notice: "2025.6 起 token 计费，重度用户月耗可达 ¥3,600 · SOC 2 Type 2 认证 · Bugbot 自动 PR 审查",
      link: "https://cursor.com", updatedAt: "2026-03-28",
    },
    {
      id: "copilot", name: "GitHub Copilot", region: "intl", category: "ide",
      badge: "180万+ 用户", badgeColor: "blue",
      desc: ["行业标准 · 10+ IDE 支持", "模型自由切换"],
      plans: [
        { name: "Free", price: 0, priceLabel: "免费", quota5h: "2,000 补全 + 50 agent", tags: ["无限补全"] },
        { name: "Pro", price: 10, priceLabel: "$10/月", quota5h: "300 premium/月", popular: true, tags: ["无限补全", "Claude Sonnet"] },
        { name: "Pro+", price: 39, priceLabel: "$39/月", quota5h: "1,500 premium/月", tags: ["全模型"] },
        { name: "Business", price: 19, priceLabel: "$19/人/月", quota5h: "团队管理", tags: ["策略管理", "审计日志"] },
        { name: "Enterprise", price: 39, priceLabel: "$39/人/月", quota5h: "知识库", tags: ["IP 赔偿", "SAML SSO"] },
      ],
      models: ["GPT-5.1", "GPT-5.2", "Claude Sonnet 4.5", "Claude Opus 4.6", "Gemini 3 Pro", "Gemini 3 Flash", "Grok Code"], contextWindow: "128K-1M",
      tools: ["VS Code", "JetBrains", "Neovim", "Xcode", "Eclipse", "Zed", "Raycast 等 10+"],
      link: "https://github.com/features/copilot", updatedAt: "2026-03-28",
    },
    {
      id: "claude-code", name: "Claude Code", region: "intl", category: "agent",
      badge: "$1B ARR", badgeColor: "purple",
      desc: ["终端原生 Agent · 推理天花板", "1M 上下文"],
      plans: [
        { name: "Free", price: 0, priceLabel: "免费", quota5h: "有限", tags: ["基础"] },
        { name: "Pro", price: 20, priceLabel: "$20/月", quota5h: "5x 用量（每5h刷新）", popular: true, tags: ["Claude Opus"] },
        { name: "Max 5x", price: 100, priceLabel: "$100/月", quota5h: "5x Pro", tags: ["更强推理"] },
        { name: "Max 20x", price: 200, priceLabel: "$200/月", quota5h: "20x Pro", tags: ["无限感"] },
        { name: "Teams", price: 150, priceLabel: "$150/人/月", quota5h: "团队级", tags: ["SSO", "合规"] },
      ],
      models: ["Claude Opus 4.6", "Claude Sonnet 4.5"], contextWindow: "1M",
      tools: ["终端 (Native)", "VS Code", "JetBrains", "Slack", "Cursor", "Windsurf"],
      notice: "仅 Anthropic 模型 · Teams $150/人/月是最大价格异类 · HIPAA ready · MCP 支持",
      link: "https://anthropic.com/claude-code", updatedAt: "2026-03-28",
    },
    {
      id: "windsurf", name: "Windsurf", region: "intl", category: "ide",
      badge: "性价比之王", badgeColor: "yellow",
      desc: ["最便宜的 Agentic IDE", "Memories 学习系统"],
      plans: [
        { name: "Free", price: 0, priceLabel: "免费", quota5h: "25 credits", tags: ["入门"] },
        { name: "Pro", price: 15, priceLabel: "$15/月", quota5h: "500 credits", popular: true, tags: ["Cascade Agent"] },
        { name: "Team", price: 30, priceLabel: "$30/人/月", quota5h: "团队协作", tags: ["协作"] },
        { name: "Enterprise", price: 60, priceLabel: "$60+/人/月", quota5h: "企业级", tags: ["管理"] },
      ],
      models: ["多模型"],
      tools: ["Windsurf IDE（VS Code based）"],
      notice: "Memories 持续学习编码模式 · 无 Background Agents · credits 计费不够透明",
      link: "https://codeium.com/windsurf", updatedAt: "2026-03-28",
    },
    {
      id: "antigravity", name: "Google Antigravity", region: "intl", category: "ide",
      badge: "免费预览", badgeColor: "green",
      desc: ["多 Agent 并行 · 内置浏览器", "Mission Control"],
      plans: [
        { name: "Free Preview", price: 0, priceLabel: "免费", quota5h: "慷慨（Beta）", popular: true, tags: ["多Agent", "浏览器"] },
        { name: "Pro", price: 20, priceLabel: "$20/月", quota5h: "Gemini 3 Ultra", tags: ["全功能"] },
      ],
      models: ["Gemini 3 Pro", "Claude Sonnet 4.5", "GPT-OSS"], contextWindow: "1M",
      tools: ["Antigravity IDE", "内置 Chromium 浏览器", "Mission Control"],
      notice: "仍在 Beta · Windows 偶有 UI 卡顿 · 无 MCP 支持 · 安全风险需注意",
      link: "https://antigravity.google", updatedAt: "2026-03-28",
    },
    {
      id: "codex", name: "OpenAI Codex", region: "intl", category: "agent",
      badge: "含 ChatGPT Plus", badgeColor: "blue",
      desc: ["云端 Agent · o3 推理", "CLI + 桌面 App"],
      plans: [
        { name: "Plus (含 Codex)", price: 20, priceLabel: "$20/月", quota5h: "ChatGPT Plus 捆绑", popular: true, tags: ["云沙箱", "CLI"] },
        { name: "Pro", price: 200, priceLabel: "$200/月", quota5h: "10x 用量", tags: ["更强"] },
      ],
      models: ["codex-1 (o3)", "GPT-5"], contextWindow: "1M",
      tools: ["Web Agent", "Codex CLI (开源)", "macOS Desktop App"],
      notice: "云沙箱零本地配置 · Desktop App 仅 macOS · 推理延迟 10-30s · 无 MCP",
      link: "https://openai.com/codex", updatedAt: "2026-03-28",
    },
    {
      id: "kiro", name: "Kiro (AWS)", region: "intl", category: "ide",
      badge: "规范驱动", badgeColor: "purple",
      desc: ["Spec-driven 开发", "Hooks + Steering"],
      plans: [
        { name: "Pro", price: 20, priceLabel: "$20/月", quota5h: "1,000 credits", tags: ["Spec", "Hooks"] },
        { name: "Pro+", price: 40, priceLabel: "$40/月", quota5h: "2,000 credits", popular: true, tags: ["更强"] },
        { name: "Power", price: 200, priceLabel: "$200/月", quota5h: "10,000 credits", tags: ["重度"] },
      ],
      models: ["AWS 模型"],
      tools: ["Kiro IDE", "MCP 支持"],
      notice: "规范驱动开发是独特优势 · 社区较小 · 有学习曲线 · 模型绑定 AWS",
      link: "https://kiro.dev", updatedAt: "2026-03-28",
    },
    {
      id: "amazon-q", name: "Amazon Q Developer", region: "intl", category: "ide",
      badge: "AWS 原生", badgeColor: "blue",
      desc: ["AWS 深度集成", "安全合规"],
      plans: [
        { name: "Individual", price: 19, priceLabel: "$19/月", quota5h: "全功能", popular: true, tags: ["按 API 计费"] },
        { name: "Enterprise", price: 0, priceLabel: "定制", quota5h: "企业级", tags: ["AWS 套餐"] },
      ],
      models: ["Amazon 自研"],
      tools: ["VS Code", "JetBrains", "IDEA", "终端"],
      notice: "通过 AWS 计费 · 无 per-request 定价 · 企业版捆绑 AWS 订阅",
      link: "https://aws.amazon.com/q/developer", updatedAt: "2026-03-28",
    },
  ],
};
